apiVersion: batch/v1
kind: CronJob
metadata:
  name: posts-bot-printtime
  namespace: ai-gateway
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: printtime
              image: freelikeatruth/posts-bot-cronjob:latest
              imagePullPolicy: IfNotPresent
              args:
                - printtime
          restartPolicy: OnFailure
