apiVersion: batch/v1
kind: CronJob
metadata:
  name: posts-bot-cronjob
  namespace: ai-gateway
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: posts-bot
              image: freelikeatruth/posts-bot-cronjob:latest
              imagePullPolicy: IfNotPresent
              args:
                - createposts
              env:
                - name: ETCD_ADDRESS
                  value: "etcd.ai-gateway:2379"
          restartPolicy: OnFailure
