FROM golang:1.24-alpine
RUN apk add --no-cache ca-certificates tzdata && \
    go install github.com/air-verse/air@v1.61.7
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
EXPOSE 8882
CMD ["air"]
