// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: service.proto

package server

import (
	"context"

	"github.com/ostapetc/ai-gateway-platform/services/comments/grpc/comments"
	"github.com/ostapetc/ai-gateway-platform/services/comments/internal/logic"
	"github.com/ostapetc/ai-gateway-platform/services/comments/internal/svc"
)

type CommentsServer struct {
	svcCtx *svc.ServiceContext
	comments.UnimplementedCommentsServer
}

func NewCommentsServer(svcCtx *svc.ServiceContext) *CommentsServer {
	return &CommentsServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentsServer) Create(ctx context.Context, in *comments.CreateRequest) (*comments.CreateResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *CommentsServer) List(ctx context.Context, in *comments.ListRequest) (*comments.ListResponse, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}
