apiVersion: v1
kind: Service
metadata:
  name: posts
  namespace: ai-gateway
spec:
  selector:
    app: posts
  ports:
    - name: http
      port: 8882
      targetPort: 8882
    - name: grpc
      port: 8885
      targetPort: 8885
