// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: service.proto

package commentsclient

import (
	"context"

	"github.com/ostapetc/ai-gateway-platform/services/comments/grpc/comments"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment        = comments.Comment
	CreateRequest  = comments.CreateRequest
	CreateResponse = comments.CreateResponse
	ListRequest    = comments.ListRequest
	ListResponse   = comments.ListResponse

	Comments interface {
		Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
		List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	}

	defaultComments struct {
		cli zrpc.Client
	}
)

func NewComments(cli zrpc.Client) Comments {
	return &defaultComments{
		cli: cli,
	}
}

func (m *defaultComments) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	client := comments.NewCommentsClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultComments) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	client := comments.NewCommentsClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}
