// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

import "time"

type AddPostRequest struct {
	UserID uint64 `json:"user_id" validate:"required"`
	Title  string `json:"title" validate:"required,min=1,max=255"`
	Body   string `json:"body" validate:"required"`
}

type AddPostResponse struct {
	ID        uint64    `json:"id"`
	UserID    uint64    `json:"user_id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type ListPostsResponse struct {
	Posts []Post `json:"posts"`
}

type GetRandomPostResponse struct {
	Post Post `json:"post"`
}

type Post struct {
	ID        uint64    `json:"id"`
	UserID    uint64    `json:"user_id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}
