volumes:
  gomodcache:

services:
  users:
    build:
      context: ../..
      dockerfile: services/users/Dockerfile.dev
    working_dir: /app/services/users
    volumes:
      - ../../:/app
      - gomodcache:/go/pkg/mod

  posts:
    build:
      context: ../..
      dockerfile: services/posts/Dockerfile.dev
    working_dir: /app/services/posts
    volumes:
      - ../../:/app
      - gomodcache:/go/pkg/mod

  comments:
    build:
      context: ../..
      dockerfile: services/comments/Dockerfile.dev
    working_dir: /app/services/comments
    volumes:
      - ../../:/app
      - gomodcache:/go/pkg/mod
