// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserRequest struct {
	Id int64 `path:"id"`
}

type GetUserResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}
