// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/ostapetc/ai-gateway-platform/services/posts/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/posts",
				Handler: AddPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: ListPostsHandler(serverCtx),
			},
		},
	)
}
