apiVersion: v1
kind: Service
metadata:
  name: otelcol
  namespace: ai-gateway
spec:
  selector:
    app: otelcol
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: prometheus
      port: 8889
      targetPort: 8889
